### ISSUE TITLE
Can't detect info for UITests

### ISSUE THREAD

**Issue by seanlucmartinez** [prashantvc/Xamarin.iOS-MessageBar#12]
Currently in the REPL, I see a MessageBar_MessageView appear for the duration of the message but it doesn't contain any info within it like the title or the text string.

**Comment by prashantvc** [comment]
This seem to get little complicated than I initially thought.
I am adding the MessageBar as a separate window on top of the existing one, and UITest fails to build a tree for it. 

I will talk to our UITest team how we can handle it better.

**Comment by seansparkman** [comment]
Any updates on this item?

**Comment by prashantvc** [comment]
This is fixed.
Please refer https://github.com/prashantvc/Xamarin.iOS-MessageBar/blob/master/MessageBarUITests/Tests.cs

**Comment by prashantvc** [comment]
@dikoga Could you update the nuget package with these changes? Looks like you're the package owner 😃
